### ISSUE TITLE
RuntimeError: Internal server error- Adding data to Custom Collection

### ISSUE THREAD

**Issue by Innarticles** [IndicoDataSolutions/IndicoIo-ruby#105]
I am trying to use Custom Collection to train my data.
This is my sample data:
 [["https://s3.eu-central-1.amazonaws.com/sfsffsdf/folder/bags/31-phillip-lim-clutch-black-blue-white-silver-4246798-0-0.jpgwidth=203&height=307", "bags"], ["https://s3.eu-central-1.amazonaws.com/sdfsdf/folder/bags/31-phillip-lim-croc-embossing-leather-satchel-black-and-red-14117848-0-1.jpgwidth=203&height=307", "bags"], ...]

And these are my lines I am running on my console: 

`
require 'indico'
Indico.api_key =  'hidden_api_key'

collection = Indico::Collection.new("folder_itemreg")
collection.add_data(data)
`
Where data is my array of array (see above sample).
From the console, this is the trace I get: 

`
RuntimeError: Internal server error
	from /home/innarticles/.rvm/gems/ruby-2.2.4/gems/indico-0.10.0/lib/indico/helper.rb:68:in `api_handler'
	from /home/innarticles/.rvm/gems/ruby-2.2.4/gems/indico-0.10.0/lib/indico.rb:189:in `_api_handler'
	from /home/innarticles/.rvm/gems/ruby-2.2.4/gems/indico-0.10.0/lib/indico.rb:203:in `add_data'
	from (irb):50

`
I need urgent help in resolving this issue:

**Comment by madisonmay** [comment]
It may be that a past failure cause the creation of a corrupt collection object? Could you try renaming the collection and repeating the steps?

**Comment by Innarticles** [comment]
OK.
I just did. Still having the same error.

**Comment by sihrc** [comment]
Those image urls don't seem to work for me. Are they public links? If not, our servers won't be able to fetch those images either.

**Comment by Innarticles** [comment]
Ok. Use the ones. I had to change edit the s3 bucket name;
[["https://s3.eu-central-1.amazonaws.com/designkit/oncenoutml/shoes/10-crosby-derek-lam-white-pumps-17384962-0-1.jpgwidth=203&height=307", "shoes"], ["https://s3.eu-central-1.amazonaws.com/designkit/oncenoutml/shoes/alexander-mcqueen-black-boots-17223136-0-1.jpgwidth=203&height=307", "shoes"]]

use this one.

**Comment by Innarticles** [comment]
Hi @madisonmay @sihrc 
I have gone ahead to try several CURL commands on my terminal including:
```shell
curl -H 'X-ApiKey: c7bxxhiddenxxxxx8a0' 'https://apiv2.indico.io/custom/collections' --data '{}'
```
And I still get 
```shell
{"error": "Internal server error"}
```
on my terminal

**Comment by madisonmay** [comment]
Hi @Innarticles,

Sorry for the slow response time, I believe your issue was fixed in a patch applied yesterday.  Let me know if things are functioning for you again.

Thanks!

--Madison
